/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cng.automation;

import cng.automation.forecourt.*;

public class App {
    public String getGreeting() {
        return "FCC Control test application!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        System.out.println("App is starting...");

        Forecourt forecourt = new DefaultForecourt();

        ForecourtSetup setup = new ForecourtSetup();
        DeviceCluster connector01 = DeviceCluster.Builder.aDeviceConnector().withId(1).withHost("127.0.0.1").withPort(10700).build();
        DeviceCluster connector02 = DeviceCluster.Builder.aDeviceConnector().withId(2).withHost("127.0.0.1").withPort(10700).build();
        connector01.addDispenser(new Dispenser(10));
        connector01.addDispenser(new Dispenser(11));
        setup.addDeviceConnector(connector01);
        setup.addDeviceConnector(connector02);


        forecourt.setSetup(setup);

        forecourt.start();



        System.out.println("App is ending...");

    }
}
